services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./:/var/www/html/phoenix-cinema.live
      - ./docker/nginx/conf.d.prod:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    container_name: nginx
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql
  app:
    build:
      context: .
      dockerfile: docker/8.3/Dockerfile
    volumes:
      - ./:/var/www/html/phoenix-cinema.live
    depends_on:
      - mysql
    container_name: app
